import js from '@eslint/js';
import typescriptEslint from 'typescript-eslint';
import importPlugin from 'eslint-plugin-import';
import unicornPlugin from 'eslint-plugin-unicorn';
import promisePlugin from 'eslint-plugin-promise';
import regexpPlugin from 'eslint-plugin-regexp';
import securityPlugin from 'eslint-plugin-security';
import sonarjsPlugin from 'eslint-plugin-sonarjs';
import perfectionistPlugin from 'eslint-plugin-perfectionist';
import noSecretsPlugin from 'eslint-plugin-no-secrets';
import nPlugin from 'eslint-plugin-n';
import globals from 'globals';

export default typescriptEslint.config(
  // Global ignores
  {
    ignores: [
      'eslint.config.ts',
      'api/**',
      'scripts/**',
      'node_modules/**',
      'dist/**',
      'data/**',
      '**/*.js',
    ],
  },

  js.configs.recommended,

  // Base configuration for all TypeScript files
  {
    files: ['**/*.ts'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
      parser: typescriptEslint.parser,
      parserOptions: {
        ecmaVersion: 2022,
        project: './tsconfig.json',
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': typescriptEslint.plugin,
      'import': importPlugin,
      'n': nPlugin,
      'no-secrets': noSecretsPlugin,
      'perfectionist': perfectionistPlugin,
      'promise': promisePlugin,
      'regexp': regexpPlugin,
      'security': securityPlugin,
      'sonarjs': sonarjsPlugin,
      'unicorn': unicornPlugin,
    },
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
          project: './tsconfig.json',
        },
      },
    },
    rules: {
      // ============================================
      // CORE JAVASCRIPT RULES
      // ============================================
      'no-console': ['error', { allow: ['error'] }],
      'no-debugger': 'error',
      'no-alert': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
      'no-eval': 'error',
      'no-implied-eval': 'off',
      'no-new-func': 'error',
      'no-param-reassign': 'error',
      'no-return-assign': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'off',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'off',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'yoda': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-template': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'no-duplicate-imports': 'error',
      'no-async-promise-executor': 'error',
      'no-implicit-globals': 'error',
      'no-promise-executor-return': 'error',

      // Restricted Syntax
      'no-restricted-syntax': [
        'error',
        {
          selector: "MemberExpression[object.property.name='constructor'][property.name='name']",
          message: 'constructor.name is unreliable after minification. Use explicit type checking instead.',
        },
        {
          selector: 'TSEnumDeclaration:not([const=true])',
          message: 'Use const enum for better tree-shaking and to avoid runtime overhead.',
        },
        {
          selector: 'UnaryExpression[operator="delete"] > MemberExpression[computed=true]',
          message: 'Do not delete array elements. Use Array.prototype.filter() or splice() instead.',
        },
        {
          selector: 'ForInStatement',
          message: 'Use Object.keys(), Object.values(), or Object.entries() with for-of instead.',
        },
        {
          selector: 'LabeledStatement',
          message: 'Labels are confusing. Refactor to avoid labels.',
        },
        {
          selector: 'WithStatement',
          message: 'with statements are deprecated and cause scope confusion.',
        },
        {
          selector: 'SequenceExpression',
          message: 'Comma operator is confusing. Use separate statements.',
        },
        {
          selector: 'IfStatement > BinaryExpression[operator="&"], IfStatement > BinaryExpression[operator="|"], IfStatement > BinaryExpression[operator="^"]',
          message: 'Bitwise operator in condition. Did you mean && or ||?',
        },
      ],

      'no-unused-vars': 'off',

      // ============================================
      // TYPESCRIPT ESLINT - CRITICAL TYPE SAFETY
      // ============================================
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/strict-boolean-expressions': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',

      // Explicit Type Annotations
      '@typescript-eslint/explicit-function-return-type': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error',

      // Code Quality
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-shadow': 'error',
      '@typescript-eslint/no-use-before-define': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/consistent-type-exports': 'error',
      '@typescript-eslint/max-params': ['error', { max: 4 }],

      // Complexity limits
      'complexity': ['error', 15],
      'max-depth': ['error', 3],
      'max-nested-callbacks': ['error', 3],
      '@typescript-eslint/prefer-readonly': 'error',
      '@typescript-eslint/promise-function-async': 'error',

      // Modern Syntax
      '@typescript-eslint/prefer-nullish-coalescing': 'error',
      '@typescript-eslint/prefer-optional-chain': 'error',
      '@typescript-eslint/prefer-as-const': 'error',
      '@typescript-eslint/prefer-string-starts-ends-with': 'error',
      '@typescript-eslint/prefer-includes': 'error',
      '@typescript-eslint/prefer-for-of': 'error',

      // Additional TypeScript Rules - ULTRA STRICT
      '@typescript-eslint/adjacent-overload-signatures': 'error',
      '@typescript-eslint/array-type': 'error',
      '@typescript-eslint/ban-ts-comment': 'error',
      '@typescript-eslint/ban-tslint-comment': 'error',
      '@typescript-eslint/class-literal-property-style': 'error',
      '@typescript-eslint/consistent-generic-constructors': 'error',
      '@typescript-eslint/consistent-indexed-object-style': 'error',
      '@typescript-eslint/consistent-type-assertions': 'error',
      '@typescript-eslint/consistent-type-definitions': 'error',
      '@typescript-eslint/default-param-last': 'error',
      '@typescript-eslint/dot-notation': 'error',
      '@typescript-eslint/explicit-member-accessibility': 'error',
      '@typescript-eslint/init-declarations': 'error',
      '@typescript-eslint/method-signature-style': 'error',
      '@typescript-eslint/no-array-constructor': 'error',
      '@typescript-eslint/no-array-delete': 'error',
      '@typescript-eslint/no-base-to-string': 'error',
      '@typescript-eslint/no-confusing-non-null-assertion': 'error',
      '@typescript-eslint/no-confusing-void-expression': 'error',
      '@typescript-eslint/no-deprecated': 'error',
      '@typescript-eslint/no-dupe-class-members': 'error',
      '@typescript-eslint/no-duplicate-enum-values': 'error',
      '@typescript-eslint/no-duplicate-type-constituents': 'error',
      '@typescript-eslint/no-dynamic-delete': 'error',
      '@typescript-eslint/no-empty-function': 'error',
      '@typescript-eslint/no-empty-object-type': 'error',
      '@typescript-eslint/no-extra-non-null-assertion': 'error',
      '@typescript-eslint/no-extraneous-class': 'error',
      '@typescript-eslint/no-for-in-array': 'error',
      '@typescript-eslint/no-implied-eval': 'error',
      '@typescript-eslint/no-import-type-side-effects': 'error',
      '@typescript-eslint/no-inferrable-types': 'error',
      '@typescript-eslint/no-invalid-this': 'error',
      '@typescript-eslint/no-invalid-void-type': 'error',
      '@typescript-eslint/no-loop-func': 'error',
      '@typescript-eslint/no-meaningless-void-operator': 'error',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-redeclare': 'error',
      '@typescript-eslint/no-redundant-type-constituents': 'error',
      '@typescript-eslint/no-require-imports': 'error',
      '@typescript-eslint/no-restricted-imports': 'error',
      '@typescript-eslint/no-this-alias': 'error',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error',
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'error',
      '@typescript-eslint/no-unnecessary-qualifier': 'error',
      '@typescript-eslint/no-unnecessary-template-expression': 'error',
      '@typescript-eslint/no-unnecessary-type-arguments': 'error',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
      '@typescript-eslint/no-unnecessary-type-constraint': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/no-unsafe-enum-comparison': 'error',
      '@typescript-eslint/no-unsafe-function-type': 'error',
      '@typescript-eslint/no-unsafe-unary-minus': 'error',
      '@typescript-eslint/no-unused-expressions': 'error',
      '@typescript-eslint/no-useless-constructor': 'error',
      '@typescript-eslint/no-useless-empty-export': 'error',
      '@typescript-eslint/no-wrapper-object-types': 'error',
      '@typescript-eslint/non-nullable-type-assertion-style': 'error',
      '@typescript-eslint/only-throw-error': 'error',
      '@typescript-eslint/parameter-properties': 'error',
      '@typescript-eslint/prefer-destructuring': 'error',
      '@typescript-eslint/prefer-enum-initializers': 'error',
      '@typescript-eslint/prefer-find': 'error',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/prefer-literal-enum-member': 'error',
      '@typescript-eslint/prefer-namespace-keyword': 'error',
      '@typescript-eslint/prefer-promise-reject-errors': 'error',
      '@typescript-eslint/prefer-reduce-type-parameter': 'error',
      '@typescript-eslint/prefer-regexp-exec': 'error',
      '@typescript-eslint/prefer-return-this-type': 'error',
      '@typescript-eslint/related-getter-setter-pairs': 'error',
      '@typescript-eslint/require-array-sort-compare': 'error',
      '@typescript-eslint/restrict-plus-operands': 'error',
      '@typescript-eslint/restrict-template-expressions': 'error',
      '@typescript-eslint/return-await': 'error',
      '@typescript-eslint/triple-slash-reference': 'error',
      '@typescript-eslint/unbound-method': 'error',
      '@typescript-eslint/unified-signatures': 'error',
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'error',

      // Bug Prevention (2025)
      '@typescript-eslint/no-misused-spread': ['error', { allow: ['string'] }],
      '@typescript-eslint/no-mixed-enums': 'error',
      '@typescript-eslint/no-unnecessary-type-parameters': 'error',
      '@typescript-eslint/no-loss-of-precision': 'error',
      '@typescript-eslint/no-unsafe-type-assertion': 'error',
      '@typescript-eslint/no-unnecessary-type-conversion': 'error',
      '@typescript-eslint/consistent-return': 'error',

      // ============================================
      // IMPORT RULES
      // ============================================
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-cycle': 'error',
      'import/no-self-import': 'error',
      'import/newline-after-import': 'error',
      'import/no-absolute-path': 'error',
      'import/no-useless-path-segments': 'error',
      'import/no-relative-packages': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'error',
      'import/no-deprecated': 'error',
      'import/no-empty-named-blocks': 'error',
      'import/no-extraneous-dependencies': ['error', { devDependencies: ['**/*.test.ts', '**/*.spec.ts', 'scripts/**/*', '*.config.*'] }],
      'import/no-amd': 'error',
      'import/no-commonjs': 'error',

      // ============================================
      // UNICORN RULES
      // ============================================
      'unicorn/better-regex': 'error',
      'unicorn/catch-error-name': 'error',
      'unicorn/consistent-destructuring': 'error',
      'unicorn/error-message': 'error',
      'unicorn/filename-case': ['error', { case: 'kebabCase' }],
      'unicorn/new-for-builtins': 'error',
      'unicorn/no-array-for-each': 'error',
      'unicorn/no-console-spaces': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-null': 'off',
      'unicorn/prefer-array-find': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/prefer-spread': 'error',
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/throw-new-error': 'error',
      'unicorn/no-array-push-push': 'error',
      'unicorn/no-empty-file': 'error',
      'unicorn/text-encoding-identifier-case': 'error',
      'unicorn/no-abusive-eslint-disable': 'error',
      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-single-promise-in-promise-methods': 'error',
      'unicorn/no-negation-in-equality-check': 'error',
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/require-array-join-separator': 'error',
      'unicorn/require-number-to-fixed-digits-argument': 'error',
      'unicorn/prefer-at': 'error',
      'unicorn/prefer-set-has': 'error',
      'unicorn/prefer-array-flat-map': 'error',
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-default-parameters': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/prefer-math-trunc': 'error',
      'unicorn/explicit-length-check': 'error',
      'unicorn/no-negated-condition': 'error',
      'unicorn/no-lonely-if': 'error',
      'unicorn/prefer-ternary': 'error',
      'unicorn/prefer-logical-operator-over-ternary': 'error',
      'unicorn/no-useless-undefined': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/consistent-assert': 'error',
      'unicorn/consistent-date-clone': 'error',
      'unicorn/consistent-empty-array-spread': 'error',
      'unicorn/consistent-existence-index-check': 'error',
      'unicorn/consistent-function-scoping': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/no-accessor-recursion': 'error',
      'unicorn/no-anonymous-default-export': 'error',
      'unicorn/no-array-method-this-argument': 'error',
      'unicorn/no-for-loop': 'error',
      'unicorn/no-hex-escape': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-magic-array-flat-depth': 'error',
      'unicorn/no-named-default': 'error',
      'unicorn/no-nested-ternary': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/no-object-as-default-parameter': 'error',
      'unicorn/no-static-only-class': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-this-assignment': 'error',
      'unicorn/no-unnecessary-array-flat-depth': 'error',
      'unicorn/no-unnecessary-array-splice-count': 'error',
      'unicorn/no-unnecessary-await': 'error',
      'unicorn/no-unnecessary-slice-end': 'error',
      'unicorn/no-unused-properties': 'error',
      'unicorn/no-useless-fallback-in-spread': 'error',
      'unicorn/no-useless-length-check': 'error',
      'unicorn/no-useless-promise-resolve-reject': 'error',
      'unicorn/no-useless-switch-case': 'error',
      'unicorn/no-zero-fractions': 'error',
      'unicorn/number-literal-case': 'error',
      'unicorn/numeric-separators-style': 'error',
      'unicorn/prefer-array-flat': 'error',
      'unicorn/prefer-array-index-of': 'error',
      'unicorn/prefer-code-point': 'error',
      'unicorn/prefer-event-target': 'error',
      'unicorn/prefer-export-from': 'error',
      'unicorn/prefer-math-min-max': 'error',
      'unicorn/prefer-modern-math-apis': 'error',
      'unicorn/prefer-native-coercion-functions': 'error',
      'unicorn/prefer-negative-index': 'error',
      'unicorn/prefer-object-from-entries': 'error',
      'unicorn/prefer-optional-catch-binding': 'error',
      'unicorn/prefer-prototype-methods': 'error',
      'unicorn/prefer-regexp-test': 'error',
      'unicorn/prefer-set-size': 'error',
      'unicorn/prefer-string-replace-all': 'error',
      'unicorn/prefer-structured-clone': 'error',
      'unicorn/prefer-switch': 'error',
      'unicorn/switch-case-braces': 'error',
      'unicorn/no-await-expression-member': 'error',
      'unicorn/no-unreadable-array-destructuring': 'error',
      'unicorn/no-unreadable-iife': 'error',
      'unicorn/prefer-string-trim-start-end': 'error',
      'unicorn/prefer-date-now': 'error',
      'unicorn/prefer-global-this': 'error',
      'unicorn/prefer-module': 'error',
      'unicorn/no-process-exit': 'off',
      'unicorn/custom-error-definition': 'error',
      'unicorn/no-array-callback-reference': 'error',
      'unicorn/no-length-as-slice-end': 'error',
      'unicorn/prefer-string-raw': 'error',

      // ============================================
      // PROMISE RULES
      // ============================================
      'promise/always-return': 'error',
      'promise/catch-or-return': 'error',
      'promise/no-nesting': 'error',
      'promise/no-return-wrap': 'error',
      'promise/param-names': 'error',

      // ============================================
      // REGEXP RULES
      // ============================================
      'regexp/no-contradiction-with-assertion': 'error',
      'regexp/no-control-character': 'error',
      'regexp/no-dupe-characters-character-class': 'error',
      'regexp/no-empty-alternative': 'error',
      'regexp/no-lazy-ends': 'error',
      'regexp/no-super-linear-backtracking': 'error',
      'regexp/optimal-quantifier-concatenation': 'error',
      'regexp/prefer-character-class': 'error',

      // ============================================
      // SECURITY RULES
      // ============================================
      'security/detect-bidi-characters': 'error',
      'security/detect-buffer-noassert': 'error',
      'security/detect-child-process': 'error',
      'security/detect-disable-mustache-escape': 'error',
      'security/detect-eval-with-expression': 'error',
      'security/detect-new-buffer': 'error',
      'security/detect-no-csrf-before-method-override': 'error',
      'security/detect-non-literal-fs-filename': 'error',
      'security/detect-non-literal-regexp': 'error',
      'security/detect-non-literal-require': 'error',
      'security/detect-object-injection': 'off',
      'security/detect-possible-timing-attacks': 'error',
      'security/detect-pseudoRandomBytes': 'error',
      'security/detect-unsafe-regex': 'error',

      // No Secrets Plugin
      'no-secrets/no-secrets': ['error', {
        tolerance: 4.2,
        ignoreContent: [
          String.raw`^\d+$`,
          '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$',
          'localhost',
          '127.0.0.1',
          '0.0.0.0',
          'example.com',
          'test@example.com',
        ],
        ignoreIdentifiers: [
          'publicKey',
          'PUBLIC_KEY',
          'userId',
          'USER_ID',
          'clientId',
          'CLIENT_ID',
        ],
      }],

      // ============================================
      // SONARJS RULES (non-React/non-web-server subset)
      // ============================================
      'sonarjs/cognitive-complexity': ['error', 15],
      'sonarjs/anchor-precedence': 'error',
      'sonarjs/argument-type': 'error',
      'sonarjs/arguments-order': 'error',
      'sonarjs/array-callback-without-return': 'error',
      'sonarjs/bitwise-operators': 'error',
      'sonarjs/call-argument-line': 'error',
      'sonarjs/class-name': 'error',
      'sonarjs/comma-or-logical-or-case': 'error',
      'sonarjs/concise-regex': 'error',
      'sonarjs/constructor-for-side-effects': 'error',
      'sonarjs/different-types-comparison': 'error',
      'sonarjs/disabled-timeout': 'error',
      'sonarjs/duplicates-in-character-class': 'error',
      'sonarjs/empty-string-repetition': 'error',
      'sonarjs/existing-groups': 'error',
      'sonarjs/for-loop-increment-sign': 'error',
      'sonarjs/function-inside-loop': 'error',
      'sonarjs/future-reserved-words': 'error',
      'sonarjs/generator-without-yield': 'error',
      'sonarjs/in-operator-type-error': 'error',
      'sonarjs/inconsistent-function-call': 'error',
      'sonarjs/index-of-compare-to-positive-number': 'error',
      'sonarjs/inverted-assertion-arguments': 'error',
      'sonarjs/label-position': 'error',
      'sonarjs/max-switch-cases': 'error',
      'sonarjs/misplaced-loop-counter': 'error',
      'sonarjs/new-operator-misuse': 'error',
      'sonarjs/no-all-duplicated-branches': 'error',
      'sonarjs/no-alphabetical-sort': 'error',
      'sonarjs/no-associative-arrays': 'error',
      'sonarjs/no-async-constructor': 'error',
      'sonarjs/no-case-label-in-switch': 'error',
      'sonarjs/no-clear-text-protocols': 'error',
      'sonarjs/no-code-after-done': 'error',
      'sonarjs/no-collapsible-if': 'error',
      'sonarjs/no-collection-size-mischeck': 'error',
      'sonarjs/no-commented-code': 'error',
      'sonarjs/no-control-regex': 'error',
      'sonarjs/no-dead-store': 'error',
      'sonarjs/no-delete-var': 'error',
      'sonarjs/no-duplicate-in-composite': 'error',
      'sonarjs/no-duplicate-string': ['error', { threshold: 3 }],
      'sonarjs/no-duplicated-branches': 'error',
      'sonarjs/no-element-overwrite': 'error',
      'sonarjs/no-empty-after-reluctant': 'error',
      'sonarjs/no-empty-alternatives': 'error',
      'sonarjs/no-empty-character-class': 'error',
      'sonarjs/no-empty-collection': 'error',
      'sonarjs/no-empty-group': 'error',
      'sonarjs/no-empty-test-file': 'error',
      'sonarjs/no-equals-in-for-termination': 'error',
      'sonarjs/no-exclusive-tests': 'error',
      'sonarjs/no-extra-arguments': 'error',
      'sonarjs/no-fallthrough': 'error',
      'sonarjs/no-for-in-iterable': 'error',
      'sonarjs/no-global-this': 'error',
      'sonarjs/no-globals-shadowing': 'error',
      'sonarjs/no-gratuitous-expressions': 'error',
      'sonarjs/no-hardcoded-ip': 'error',
      'sonarjs/no-hardcoded-passwords': 'error',
      'sonarjs/no-hardcoded-secrets': 'error',
      'sonarjs/no-identical-conditions': 'error',
      'sonarjs/no-identical-expressions': 'error',
      'sonarjs/no-identical-functions': 'error',
      'sonarjs/no-ignored-exceptions': 'error',
      'sonarjs/no-ignored-return': 'error',
      'sonarjs/no-implicit-global': 'error',
      'sonarjs/no-in-misuse': 'error',
      'sonarjs/no-incomplete-assertions': 'error',
      'sonarjs/no-incorrect-string-concat': 'error',
      'sonarjs/no-internal-api-use': 'error',
      'sonarjs/no-invalid-regexp': 'error',
      'sonarjs/no-invariant-returns': 'error',
      'sonarjs/no-inverted-boolean-check': 'error',
      'sonarjs/no-ip-forward': 'error',
      'sonarjs/no-labels': 'error',
      'sonarjs/no-literal-call': 'error',
      'sonarjs/no-misleading-array-reverse': 'error',
      'sonarjs/no-misleading-character-class': 'error',
      'sonarjs/no-mixed-content': 'error',
      'sonarjs/no-nested-assignment': 'error',
      'sonarjs/no-nested-conditional': 'error',
      'sonarjs/no-nested-functions': 'error',
      'sonarjs/no-nested-switch': 'error',
      'sonarjs/no-nested-template-literals': 'error',
      'sonarjs/no-os-command-from-path': 'error',
      'sonarjs/no-parameter-reassignment': 'off',
      'sonarjs/no-primitive-wrappers': 'error',
      'sonarjs/no-redundant-assignments': 'error',
      'sonarjs/no-redundant-boolean': 'error',
      'sonarjs/no-redundant-jump': 'error',
      'sonarjs/no-redundant-optional': 'error',
      'sonarjs/no-regex-spaces': 'error',
      'sonarjs/no-same-argument-assert': 'error',
      'sonarjs/no-same-line-conditional': 'error',
      'sonarjs/no-skipped-tests': 'error',
      'sonarjs/no-small-switch': 'error',
      'sonarjs/no-try-promise': 'error',
      'sonarjs/no-undefined-argument': 'error',
      'sonarjs/no-unenclosed-multiline-block': 'error',
      'sonarjs/no-unsafe-unzip': 'error',
      'sonarjs/no-unthrown-error': 'error',
      'sonarjs/no-unused-collection': 'error',
      'sonarjs/no-unused-vars': 'off',
      'sonarjs/no-use-of-empty-return-value': 'error',
      'sonarjs/no-useless-catch': 'error',
      'sonarjs/no-useless-increment': 'error',
      'sonarjs/no-useless-intersection': 'error',
      'sonarjs/non-existent-operator': 'error',
      'sonarjs/null-dereference': 'error',
      'sonarjs/prefer-default-last': 'error',
      'sonarjs/prefer-immediate-return': 'error',
      'sonarjs/prefer-object-literal': 'error',
      'sonarjs/prefer-promise-shorthand': 'error',
      'sonarjs/prefer-regexp-exec': 'off',
      'sonarjs/prefer-single-boolean-return': 'error',
      'sonarjs/prefer-type-guard': 'error',
      'sonarjs/prefer-while': 'error',
      'sonarjs/public-static-readonly': 'error',
      'sonarjs/reduce-initial-value': 'error',
      'sonarjs/redundant-type-aliases': 'error',
      'sonarjs/regex-complexity': 'error',
      'sonarjs/single-char-in-character-classes': 'error',
      'sonarjs/single-character-alternation': 'error',
      'sonarjs/slow-regex': 'error',
      'sonarjs/stable-tests': 'error',
      'sonarjs/stateful-regex': 'error',
      'sonarjs/unused-import': 'error',
      'sonarjs/unused-named-groups': 'error',
      'sonarjs/updated-const-var': 'error',
      'sonarjs/updated-loop-counter': 'error',
      'sonarjs/use-type-alias': 'error',
      'sonarjs/void-use': 'error',

      // SonarJS Security (applicable to Node.js CLI)
      'sonarjs/confidential-information-logging': 'error',
      'sonarjs/deprecation': 'off',
      'sonarjs/disabled-auto-escaping': 'error',
      'sonarjs/encryption-secure-mode': 'error',
      'sonarjs/file-permissions': 'error',
      'sonarjs/hashing': 'error',
      'sonarjs/hidden-files': 'error',
      'sonarjs/insecure-jwt-token': 'error',
      'sonarjs/no-mime-sniff': 'error',
      'sonarjs/no-weak-cipher': 'error',
      'sonarjs/no-weak-keys': 'error',
      'sonarjs/os-command': 'error',
      'sonarjs/production-debug': 'error',
      'sonarjs/pseudo-random': 'error',
      'sonarjs/publicly-writable-directories': 'error',
      'sonarjs/sql-queries': 'error',
      'sonarjs/unverified-certificate': 'error',
      'sonarjs/unverified-hostname': 'error',
      'sonarjs/weak-ssl': 'error',
      'sonarjs/xml-parser-xxe': 'error',

      // SonarJS Testing
      'sonarjs/assertions-in-tests': 'error',
      'sonarjs/chai-determinate-assertion': 'error',
      'sonarjs/fixme-tag': 'error',
      'sonarjs/test-check-exception': 'error',
      'sonarjs/todo-tag': 'error',

      // ============================================
      // NODE.JS RULES
      // ============================================
      'n/no-deprecated-api': 'error',
      'n/no-exports-assign': 'error',

      // ============================================
      // PERFECTIONIST - CODE ORGANIZATION & SORTING
      // ============================================
      'perfectionist/sort-imports': ['error', {
        type: 'natural',
        order: 'asc',
        groups: [
          'type',
          'builtin',
          'external',
          'internal',
          'parent',
          'sibling',
          'index',
          'unknown',
        ],
        newlinesBetween: 'ignore',
      }],
      'perfectionist/sort-named-imports': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-named-exports': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-exports': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-object-types': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-interfaces': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-union-types': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-intersection-types': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-enums': ['error', { type: 'natural', order: 'asc' }],
      'perfectionist/sort-switch-case': ['error', { type: 'natural', order: 'asc' }],
    },
  },

  // Database + tools + index: better-sqlite3 returns unknown types, MCP SDK requires broad union casts
  {
    files: ['src/tools/**/*.ts', 'src/db.ts', 'src/index.ts', 'src/server.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
    },
  },

  // Database path resolution uses resolve() — paths are safe, not user input
  {
    files: ['src/db.ts'],
    rules: {
      'security/detect-non-literal-fs-filename': 'off',
    },
  },

  // Auth: JWT payloads are verified then cast to known shapes
  {
    files: ['src/auth/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
    },
  },

  // Tool SQL queries are parameterized and safe
  {
    files: ['src/tools/**/*.ts'],
    rules: {
      'sonarjs/sql-queries': 'off',
    },
  },

  // Arabic grammar engine — inherent complexity from ported grammar rules
  {
    files: ['src/lib/arabic-grammar.ts'],
    rules: {
      'sonarjs/cognitive-complexity': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'complexity': 'off',
      'max-depth': 'off',
    },
  },

  // MCP server files — Server is the correct low-level API (McpServer is high-level)
  {
    files: ['src/index.ts', 'src/server.ts'],
    rules: {
      '@typescript-eslint/no-deprecated': 'off',
    },
  },

  // Express handler patterns: callback-style handlers with unused params
  {
    files: ['src/index.ts'],
    rules: {
      'no-console': ['error', { allow: ['error', 'log'] }],
    },
  },
);
